credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: $2b$12$mUBEgrvsX0cFDwTC31aKEexWm25IICM03edQgJyj.D9RRRZ8r8rrW # To be replaced with hashed password
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: $2b$12$Fpx7emjXoDo8YQKPAuMqkuI9yVE4DeN/Y1Lf2SCll7drVhcAv7Lba # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com